### ISSUE TITLE
TypeLite.tt file not being generated

### ISSUE THREAD

**Issue by nickmkk** [CloudNimble/TypeLitePlus#2]
When I install this package it doesn't create the TypeLite.tt file as stated in the original documentation.  Has that behavior changed or am I missing something?

**Comment by robertmclaws** [comment]
If you are installing it in a project that uses <PackageReference> instead of packages.config, NuGet will no longer drop files in your project. It sucks, we know, and there is nothing we can do about it. But you CAN [pull the file from the repo](https://github.com/CloudNimble/TypeLitePlus/blob/master/TypeLitePlus.T4/Scripts/TypeLite.tt) and do it yourself.

We're looking into alternatives, like registering a tool with `dotnet` so it can drop the file in for you at the command line.

**Comment by robertmclaws** [comment]
Hey! I know this post is old, but just so you know, we have a version now that works with DotNetScript. You can see this sample file for details: https://github.com/CloudNimble/TypeLitePlus/blob/master/TypeLitePlus.DotNetScript/TypeLite.csx

HTH!
